apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hpa-deployment
  labels:
    app: php-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-hpa
  template:
    metadata:
      labels:
        app: php-hpa
    spec:
      containers:
      - name: php-hpa
        image: registry.cn-hangzhou.aliyuncs.com/larswang/php-hpa:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: php-hpa-service
spec:
  type: ClusterIP
  selector:
    app: php-hpa
  ports:
    - port: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-hpa-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
